apiVersion: v2
name: flyimg
description: A Helm chart for Kubernetes for Flyimg app
type: application
maintainers:
  - name: sadok-f
    email: sadoknet@gmail.com
    url: https://github.com/sadok-f

keywords:
  - flyimg
  - image-resizing
  - image-optimization
  - avif
  - mozjpeg
  - webp

version: 0.2.1

appVersion: 1.4.12
